WIP: test micromamba simplifications

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -48,6 +48,10 @@ jobs:
       matrix:
         python-version: ["3.8"]
     steps:
+    - name: Cancel Previous Runs
+        uses: styfle/cancel-workflow-action@0.6.0
+        with:
+          access_token: ${{ github.token }}
     - uses: actions/checkout@v2
       with:
         fetch-depth: 0
@@ -62,7 +66,7 @@ jobs:
     - name: Install deps
       run: |
         micromamba create --yes -n wradlib-tests python=${{ matrix.python-version }} --file requirements.txt --file requirements_devel.txt --channel conda-forge
-        echo "set -eo pipefail" >> "HOME/.bash_profile"
+        echo "set -eo pipefail" >> "$HOME/.bash_profile"
         echo "micromamba activate wradlib-tests" >> "$HOME/.bash_profile"
     - name: Install wradlib
       run: |
